export const AUTH = 'AUTH'
export const LOGOUT = 'LOGOUT'

export const JOIN_CALL = 'JOIN_CALL'
export const GET_INTERVIEW_ANALYSIS = 'GET_INTERVIEW_ANALYSIS'
export const STOP_ANALYSIS = 'STOP_ANALYSIS'

export const SEND_VIDEO_DATA = 'SEND_VIDEO_DATA'
export const GET_CONVO_LIST = 'GET_CONVO_LIST'
export const GET_COMPARISON_DATA = 'GET_COMPARISON_DATA'
export const FETCH_ANALYSIS_RESULT = 'FETCH_ANALYSIS_RESULT'

